{{- if .Values.makaroni.image.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.makaroni.image.secret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.makaroni.image.secret.dockerconfigjson | b64enc }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "makaroni.fullname" . }}
spec:
  replicas: {{ .Values.makaroni.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "makaroni.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "makaroni.name" . }}
    spec:
      {{- if .Values.makaroni.image.secret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.makaroni.image.secret.name }}
      {{- end }}
      containers:
        - name: makaroni
          image: "{{ .Values.makaroni.image.repository }}:{{ .Values.makaroni.image.tag }}"
          command:
            - ./makaroni
          env:
            - name: LOG_LEVEL
              value: {{ .Values.makaroni.config.logLevel | quote }}
            - name: MKRN_ADDRESS
              value: {{ .Values.makaroni.config.address | quote }}
            - name: MKRN_MULTIPART_MAX_MEMORY
              value: {{ .Values.makaroni.config.multipartMaxMemory | quote }}
            - name: MKRN_INDEX_URL
              value: {{ .Values.makaroni.config.indexUrl | quote }}
            - name: MKRN_RESULT_URL_PREFIX
              value: {{ .Values.makaroni.config.resultUrlPrefix | quote }}
            - name: MKRN_LOGO_URL
              value: {{ .Values.makaroni.config.logoUrl | quote }}
            - name: MKRN_FAVICON_URL
              value: {{ .Values.makaroni.config.faviconUrl | quote }}
            - name: MKRN_STYLE
              value: {{ .Values.makaroni.config.style | quote }}
            - name: MKRN_S3_ENDPOINT
              value: {{ .Values.makaroni.config.s3Endpoint | quote }}
            - name: MKRN_S3_PATH_STYLE
              value: {{ .Values.makaroni.config.s3PathStyle | quote }}
            - name: MKRN_S3_DISABLE_SSL
              value: {{ .Values.makaroni.config.s3DisableSsl | quote }}
            - name: MKRN_S3_REGION
              value: {{ .Values.makaroni.config.s3Region | quote }}
            - name: MKRN_S3_BUCKET
              value: {{ .Values.makaroni.config.s3Bucket | quote }}
            - name: MKRN_S3_KEY_ID
              value: {{ .Values.makaroni.config.s3KeyId | quote }}
            - name: MKRN_S3_SECRET_KEY
              value: {{ .Values.makaroni.config.s3SecretKey | quote }}
          ports:
            - containerPort: 8080
