apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "makaroni.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "makaroni.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "makaroni.name" . }}
    spec:
      containers:
      - name: makaroni
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: MKRN_ADDRESS
          value: {{ .Values.config.address | quote }}
        - name: MKRN_MULTIPART_MAX_MEMORY
          value: {{ .Values.config.multipartMaxMemory | quote }}
        - name: MKRN_INDEX_URL
          value: {{ .Values.config.indexUrl | quote }}
        - name: MKRN_RESULT_URL_PREFIX
          value: {{ .Values.config.resultUrlPrefix | quote }}
        - name: MKRN_LOGO_URL
          value: {{ .Values.config.logoUrl | quote }}
        - name: MKRN_FAVICON_URL
          value: {{ .Values.config.faviconUrl | quote }}
        - name: MKRN_STYLE
          value: {{ .Values.config.style | quote }}
        - name: MKRN_S3_ENDPOINT
          value: {{ .Values.config.s3Endpoint | quote }}
        - name: MKRN_S3_REGION
          value: {{ .Values.config.s3Region | quote }}
        - name: MKRN_S3_BUCKET
          value: {{ .Values.config.s3Bucket | quote }}
        - name: MKRN_S3_KEY_ID
          value: {{ .Values.config.s3KeyId | quote }}
        - name: MKRN_S3_SECRET_KEY
          value: {{ .Values.config.s3SecretKey | quote }}
        ports:
        - containerPort: 80
