{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "makaroni.fullname" . }}-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "makaroni.name" . }}-minio
  template:
    metadata:
      labels:
        app: {{ include "makaroni.name" . }}-minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image }}:{{ .Values.minio.tag }}"
          {{- if .Values.minio.consolePort }}
          command: ['sh', '-c', 'mkdir -p /data/{{ .Values.makaroni.config.s3Bucket }} && /usr/bin/minio server /data --console-address=:9090 &; && mc alias set myminio http://localhost:9000 {{ .Values.minio.rootUser }} {{ .Values.minio.rootPassword }} && mc anonymous set public myminio/{{ .Values.makaroni.config.s3Bucket }}' ]
          {{- end }}
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.rootPassword | quote }}
          ports:
            - containerPort: {{ .Values.minio.servicePort }}
            {{- if .Values.minio.consolePort }}
            - containerPort: {{ .Values.minio.consolePort }}
            {{- end }}
{{- end }}