{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "makaroni.fullname" . }}-minio
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.minio.servicePort }}
      targetPort: {{ .Values.minio.servicePort }}
      name: s3
    {{- if .Values.minio.consolePort }}
    - port: {{ .Values.minio.consolePort }}
      targetPort: {{ .Values.minio.consolePort }}
      name: console
    {{- end }}
  selector:
    app: {{ include "makaroni.name" . }}-minio
---

{{- end }}