apiVersion: v1
kind: Service
metadata:
  name: {{ include "makaroni.fullname" . }}
spec:
  type: {{ .Values.makaroni.service.type }}
  ports:
    - port: {{ .Values.makaroni.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "makaroni.name" . }}
